### ISSUE TITLE
 What are the differences between the "Jun-Chef" application versions 1 and 2?

### ISSUE THREAD

**Issue by qortmdgh4141** [jjunsik/Jun-Chef2#1]
I was wondering if you could provide some insights into the differences between version 1 and version 2 of the "Jun-Chef" application. Are there any notable features that have been upgraded from the previous version? It would be great to know how the user experience has evolved and what new capabilities we can look forward to.

Additionally, I'm quite curious about the anticipated completion date for the development of version 2. As a user who has benefited from the current version, knowing when the new and improved version will be available would be greatly appreciated.

**Comment by jjunsik** [comment]
First of all, thank you for using "Jun-Chef".

After finishing "Jun-Chef" version.1, additional requirements were
identified through interviews with customers (users of "Jun-Chef"
version.1).
And while developing "Jun-Chef" version.1, "Search time is long." and to
solve it, the "Jun-Chef" application advancement project was planned.

Customers' additional requirements include "Favorites" and "My Recipe", and
we plan to implement a login function for this purpose.
And, as a solution to the search time problem, the recipe information is
stored in the DB.
Through this, it is expected that the search time can be shortened by
directly providing the recipe information stored in the DB rather than
communicating with ChatGPT.

This advancement project is "Jun-Chef" version.2, and we plan to migrate
the search function within the "Jun-Chef" application to the server by
creating a server as well as applying the aforementioned user requirements
and improving the search function.

We are currently developing the server, and we will proceed with other
tasks after the server development is complete.
The goal is to complete the upgrade project within the month of August.

Thank you for your interest in "Jun-Chef".

2023년 8월 15일 (화) 오후 8:48, Seungho Baek ***@***.***>님이 작성:
